import sys
import os
import m_sequence
import scrambling
import gold
import random as rnd
import sequence_converter as seq_conv

print("DESCRAMBLER")
print("Your file should have one line constisting of zeros and ones. No commas, no white spaces, no dots, no JSON structures, just zeros and ones like this: 0101010101")
while True:
    try:
        user_file_input = raw_input("Enter the path of the file which content you want to descramble: ")

        assert os.path.exists(user_file_input)
        f = open(user_file_input, 'r+')
        break
    except AssertionError:
        print "I did not find the file at " + str(user_file_input)
        continue
sequence = f.read().rstrip()
print('OK, I read your input. Please, be aware that the scrambler reads ONLY one, first line. Your file is:\n') + str(sequence)
sequence = seq_conv.transform_string_to_array(sequence)

while True:
    try:
        gold_code_filepath = raw_input("Enter the path of the file with the Gold code generated by the scrambler: ")

        assert os.path.exists(gold_code_filepath)
        f = open(gold_code_filepath, 'r+')
        break
    except AssertionError:
        print "I did not find the file at " +str(gold_code_filepath)
        continue

gold_code = seq_conv.transform_string_to_array(f.read().rstrip())

descrambler = scrambling.Descrambler(gold_code)
descrambled_sequence_filename = 'descrambled_output.txt'
descrambled_sequence = open(descrambled_sequence_filename, 'w+')
descrambled_sequence.write(seq_conv.transform_array_to_string(descrambler.descramble(sequence)))
descrambled_sequence.close()
print 'The descrambled sequence was written to file: ' + descrambled_sequence_filename + '. Thanks for using our scrambler and descrambler!'

f.close()